sudo: required
dist: trusty
language: fortran

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BTYPE=Release
#    - os: linux
#      compiler: clang
#      env: BTYPE=RelWithDebInfo
#    - os: linux
#      compiler: clang
#      env: BTYPE=Debug
#    - os: linux
#      compiler: gcc
#      env: BTYPE=Coverage
#    - os: osx
#      compiler: clang
#      env: BTYPE=RelWithDebInfo

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install g++; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install gfortran; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install gmsh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install autoconf; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install libtool; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install python-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install python-scipy; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install python-matplotlib; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install python-mpi4py; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install python-tk; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install openmpi-bin; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install libopenmpi-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install dvipng; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install cvs; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install automake; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install libblitz0-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get --yes install libblitz0ldbl; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw --with-fortran; fi

install:
  - make

script:
  # Create package
  - make package
#  - make package
#  # Make sure we can install with no issues.
#  - make install
#  # Create coverage report
#  - if [[ "$BTYPE" == "Coverage" ]];
#    then
#    echo "Coverage";
#    find $TRAVIS_BUILD_DIR -type f -name "*.gcno";
#    find $TRAVIS_BUILD_DIR -type f -name "*.gcna";
#    make coverage;
#    bash <(curl -s https://codecov.io/bash) -X gcov;
#    fi
